import { z } from "zod";
import { withApplicationConnection } from "../../utils/ConnectionManager.js";
import type { DomainToolDefinition } from "../domainRuntime.js";

const canonicalInputShape = {
  action: z.enum([
    "check_alignment",
    "check_profile",
    "check_corridor",
    "check_pipe_network",
    "check_surface",
    "check_labels",
    "check_drawing_standards",
    "fix_drawing_standards",
    "generate_report",
  ]).describe("The QC operation to perform."),
  name: z.string().optional(),
  designSpeed: z.number().optional(),
  checkTangents: z.boolean().optional(),
  checkCurves: z.boolean().optional(),
  checkSpirals: z.boolean().optional(),
  alignmentName: z.string().optional(),
  profileName: z.string().optional(),
  maxGrade: z.number().optional(),
  minKValue: z.number().optional(),
  minCover: z.number().optional(),
  maxSlope: z.number().optional(),
  minSlope: z.number().optional(),
  minVelocity: z.number().optional(),
  maxVelocity: z.number().optional(),
  spikeThreshold: z.number().optional(),
  flatTriangleThreshold: z.number().optional(),
  objectType: z.string().optional(),
  checkMissing: z.boolean().optional(),
  checkStyleViolations: z.boolean().optional(),
  layerPrefix: z.string().optional(),
  checkLineweights: z.boolean().optional(),
  checkColors: z.boolean().optional(),
  fixSpaces: z.boolean().optional(),
  maxNameLength: z.number().optional(),
  colorIndex: z.number().optional(),
  lineweight: z.number().optional(),
  dryRun: z.boolean().optional(),
  outputPath: z.string().optional(),
  overwrite: z.boolean().optional(),
  includeAlignments: z.boolean().optional(),
  includeProfiles: z.boolean().optional(),
  includeCorridors: z.boolean().optional(),
  includePipeNetworks: z.boolean().optional(),
  includeSurfaces: z.boolean().optional(),
  includeLabels: z.boolean().optional(),
};

export const QC_DOMAIN_DEFINITION: DomainToolDefinition = {
  domain: "qc",
  actions: {
    check_alignment: {
      action: "check_alignment",
      inputSchema: z.object({
        action: z.literal("check_alignment"),
        name: z.string(),
        designSpeed: z.number().positive().optional(),
        checkTangents: z.boolean().optional(),
        checkCurves: z.boolean().optional(),
        checkSpirals: z.boolean().optional(),
      }),
      capabilities: ["query", "analyze"],
      requiresActiveDrawing: true,
      safeForRetry: true,
      pluginMethods: ["qcCheckAlignment"],
      execute: async (args: any) => await withApplicationConnection(async (c) =>
        await c.sendCommand("qcCheckAlignment", {
          name: args.name,
          designSpeed: args.designSpeed ?? null,
          checkTangents: args.checkTangents ?? true,
          checkCurves: args.checkCurves ?? true,
          checkSpirals: args.checkSpirals ?? true,
        })),
    },
    check_profile: {
      action: "check_profile",
      inputSchema: z.object({
        action: z.literal("check_profile"),
        alignmentName: z.string(),
        profileName: z.string(),
        maxGrade: z.number().positive().optional(),
        minKValue: z.number().positive().optional(),
      }),
      capabilities: ["query", "analyze"],
      requiresActiveDrawing: true,
      safeForRetry: true,
      pluginMethods: ["qcCheckProfile"],
      execute: async (args: any) => await withApplicationConnection(async (c) =>
        await c.sendCommand("qcCheckProfile", {
          alignmentName: args.alignmentName,
          profileName: args.profileName,
          maxGrade: args.maxGrade ?? null,
          minKValue: args.minKValue ?? null,
        })),
    },
    check_corridor: {
      action: "check_corridor",
      inputSchema: z.object({ action: z.literal("check_corridor"), name: z.string() }),
      capabilities: ["query", "analyze"],
      requiresActiveDrawing: true,
      safeForRetry: true,
      pluginMethods: ["qcCheckCorridor"],
      execute: async (args: any) => await withApplicationConnection(async (c) =>
        await c.sendCommand("qcCheckCorridor", { name: args.name })),
    },
    check_pipe_network: {
      action: "check_pipe_network",
      inputSchema: z.object({
        action: z.literal("check_pipe_network"),
        name: z.string(),
        minCover: z.number().nonnegative().optional(),
        maxSlope: z.number().positive().optional(),
        minSlope: z.number().nonnegative().optional(),
        minVelocity: z.number().nonnegative().optional(),
        maxVelocity: z.number().positive().optional(),
      }),
      capabilities: ["query", "analyze"],
      requiresActiveDrawing: true,
      safeForRetry: true,
      pluginMethods: ["qcCheckPipeNetwork"],
      execute: async (args: any) => await withApplicationConnection(async (c) =>
        await c.sendCommand("qcCheckPipeNetwork", {
          name: args.name,
          minCover: args.minCover ?? null,
          maxSlope: args.maxSlope ?? null,
          minSlope: args.minSlope ?? null,
          minVelocity: args.minVelocity ?? null,
          maxVelocity: args.maxVelocity ?? null,
        })),
    },
    check_surface: {
      action: "check_surface",
      inputSchema: z.object({
        action: z.literal("check_surface"),
        name: z.string(),
        spikeThreshold: z.number().positive().optional(),
        flatTriangleThreshold: z.number().nonnegative().optional(),
      }),
      capabilities: ["query", "analyze"],
      requiresActiveDrawing: true,
      safeForRetry: true,
      pluginMethods: ["qcCheckSurface"],
      execute: async (args: any) => await withApplicationConnection(async (c) =>
        await c.sendCommand("qcCheckSurface", {
          name: args.name,
          spikeThreshold: args.spikeThreshold ?? null,
          flatTriangleThreshold: args.flatTriangleThreshold ?? null,
        })),
    },
    check_labels: {
      action: "check_labels",
      inputSchema: z.object({
        action: z.literal("check_labels"),
        objectType: z.string().optional(),
        checkMissing: z.boolean().optional(),
        checkStyleViolations: z.boolean().optional(),
      }),
      capabilities: ["query", "analyze"],
      requiresActiveDrawing: true,
      safeForRetry: true,
      pluginMethods: ["qcCheckLabels"],
      execute: async (args: any) => await withApplicationConnection(async (c) =>
        await c.sendCommand("qcCheckLabels", {
          objectType: args.objectType ?? null,
          checkMissing: args.checkMissing ?? true,
          checkStyleViolations: args.checkStyleViolations ?? true,
        })),
    },
    check_drawing_standards: {
      action: "check_drawing_standards",
      inputSchema: z.object({
        action: z.literal("check_drawing_standards"),
        layerPrefix: z.string().optional(),
        checkLineweights: z.boolean().optional(),
        checkColors: z.boolean().optional(),
      }),
      capabilities: ["query", "analyze"],
      requiresActiveDrawing: true,
      safeForRetry: true,
      pluginMethods: ["qcCheckDrawingStandards"],
      execute: async (args: any) => await withApplicationConnection(async (c) =>
        await c.sendCommand("qcCheckDrawingStandards", {
          layerPrefix: args.layerPrefix ?? null,
          checkLineweights: args.checkLineweights ?? false,
          checkColors: args.checkColors ?? false,
        })),
    },
    fix_drawing_standards: {
      action: "fix_drawing_standards",
      inputSchema: z.object({
        action: z.literal("fix_drawing_standards"),
        layerPrefix: z.string().optional(),
        fixSpaces: z.boolean().optional(),
        maxNameLength: z.number().int().positive().optional(),
        colorIndex: z.number().int().optional(),
        lineweight: z.number().int().optional(),
        dryRun: z.boolean().optional(),
      }),
      capabilities: ["edit", "manage"],
      requiresActiveDrawing: true,
      safeForRetry: false,
      pluginMethods: ["qcFixDrawingStandards"],
      execute: async (args: any) => await withApplicationConnection(async (c) =>
        await c.sendCommand("qcFixDrawingStandards", {
          layerPrefix: args.layerPrefix ?? null,
          fixSpaces: args.fixSpaces ?? true,
          maxNameLength: args.maxNameLength ?? 64,
          colorIndex: args.colorIndex ?? null,
          lineweight: args.lineweight ?? null,
          dryRun: args.dryRun ?? false,
        })),
    },
    generate_report: {
      action: "generate_report",
      inputSchema: z.object({
        action: z.literal("generate_report"),
        outputPath: z.string(),
        overwrite: z.boolean().optional(),
        includeAlignments: z.boolean().optional(),
        includeProfiles: z.boolean().optional(),
        includeCorridors: z.boolean().optional(),
        includePipeNetworks: z.boolean().optional(),
        includeSurfaces: z.boolean().optional(),
        includeLabels: z.boolean().optional(),
      }),
      capabilities: ["query", "analyze", "generate"],
      requiresActiveDrawing: true,
      safeForRetry: false,
      pluginMethods: ["qcReportGenerate"],
      execute: async (args: any) => await withApplicationConnection(async (c) =>
        await c.sendCommand("qcReportGenerate", {
          outputPath: args.outputPath,
          overwrite: args.overwrite ?? false,
          includeAlignments: args.includeAlignments ?? true,
          includeProfiles: args.includeProfiles ?? true,
          includeCorridors: args.includeCorridors ?? true,
          includePipeNetworks: args.includePipeNetworks ?? true,
          includeSurfaces: args.includeSurfaces ?? true,
          includeLabels: args.includeLabels ?? true,
        })),
    },
  },
  exposures: [
    {
      toolName: "civil3d_qc",
      displayName: "Civil 3D QC",
      description: "Runs Civil 3D quality-control checks for alignments, profiles, corridors, pipe networks, surfaces, labels/styles, and drawing (layer) standards, plus consolidated QC reporting, through a single domain tool.",
      inputShape: canonicalInputShape,
      supportedActions: [
        "check_alignment",
        "check_profile",
        "check_corridor",
        "check_pipe_network",
        "check_surface",
        "check_labels",
        "check_drawing_standards",
        "fix_drawing_standards",
        "generate_report",
      ],
      resolveAction: (rawArgs) => ({ action: String(rawArgs.action ?? ""), args: rawArgs }),
    },
  ],
};
